//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFantasy14API.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Class_Skills
    {
        public int Class_SkillsId { get; set; }
        public Nullable<int> FFClassId { get; set; }
        public Nullable<int> SkillsId { get; set; }
        public Nullable<int> Skills_SkillId { get; set; }
    
        public virtual Skill Skill { get; set; }
        public virtual FFClass FFClass { get; set; }
    }
}
