//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFantasy14API.Dal
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class FF14Context : DbContext
    {
        public FF14Context()
            : base("name=FF14Context")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<C__MigrationHistory> C__MigrationHistory { get; set; }
        public virtual DbSet<Class_Skills> Class_Skills { get; set; }
        public virtual DbSet<Class_Traits> Class_Traits { get; set; }
        public virtual DbSet<FFClass> FFClasses { get; set; }
        public virtual DbSet<Job_Skills> Job_Skills { get; set; }
        public virtual DbSet<Job_Traits> Job_Traits { get; set; }
        public virtual DbSet<Job> Jobs { get; set; }
        public virtual DbSet<Skill> Skills { get; set; }
        public virtual DbSet<sysdiagram> sysdiagrams { get; set; }
        public virtual DbSet<Trait> Traits { get; set; }
    }
}
