//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFantasy14API.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Job()
        {
            this.Job_Skills = new HashSet<Job_Skills>();
            this.Job_Traits = new HashSet<Job_Traits>();
        }
    
        public int JobId { get; set; }
        public string JobName { get; set; }
        public string Role { get; set; }
        public string PrimaryClassRequirement { get; set; }
        public string subClassRequirement { get; set; }
        public Nullable<int> FFClassId { get; set; }
        public string WeaponType { get; set; }
    
        public virtual FFClass FFClass { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Skills> Job_Skills { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Traits> Job_Traits { get; set; }
    }
}
