//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFantasy14API.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Job_Skills
    {
        public int Job_SkillsId { get; set; }
        public int JobId { get; set; }
        public int SkillsId { get; set; }
        public Nullable<int> Skill_SkillId { get; set; }
    
        public virtual Job Job { get; set; }
        public virtual Skill Skill { get; set; }
    }
}
