//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FinalFantasy14API.Dal
{
    using System;
    using System.Collections.Generic;
    
    public partial class Trait
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Trait()
        {
            this.Class_Traits = new HashSet<Class_Traits>();
            this.Job_Traits = new HashSet<Job_Traits>();
        }
    
        public int TraitId { get; set; }
        public string TraitName { get; set; }
        public string LevelAcquired { get; set; }
        public string Description { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Class_Traits> Class_Traits { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Job_Traits> Job_Traits { get; set; }
    }
}
